# Generated by Django 3.1.7 on 2021-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_company', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=20)),
                ('c_price', models.CharField(max_length=20)),
            ],
        ),
    ]
